#!/usr/bin/env ruby
# frozen_string_literal: true

# Adds the VzhukhTunnel packet tunnel extension to ios/Runner.xcodeproj.
#
# The Xcode project is generated by `flutter create` and is not something
# anybody edits by hand twice, so the target is described here instead. Running
# this again replaces what it made last time, which means `flutter create` can
# regenerate the project without the extension being lost for good.
#
# Usage:
#   ruby scripts/setup_ios_extension.rb            # add the extension
#   ruby scripts/setup_ios_extension.rb remove     # take it back out
#
# The remove mode exists because the entitlement the extension needs,
# packet-tunnel-provider, is not available to a free Personal Team: Xcode
# refuses to produce a profile at all, and the app cannot be installed even to
# look at its UI. Removing the extension gives back a project that builds and
# runs on a device, with no tunnel in it.

require 'xcodeproj'

ROOT = File.expand_path('..', __dir__)
PROJECT_PATH = File.join(ROOT, 'ios', 'Runner.xcodeproj')

EXTENSION_NAME = 'VzhukhTunnel'
SHARED_GROUP = 'Shared'
APP_BUNDLE_ID = 'dev.nogipx.vzhukh'
EXTENSION_BUNDLE_ID = "#{APP_BUNDLE_ID}.tunnel"

# The personal team. The work account (563A6P64BA, albion) must not end up
# here.
TEAM_ID = '3KCLFXFC74'

DEPLOYMENT_TARGET = '13.0'
SHARED_SOURCES = %w[TunnelConfiguration.swift TunnelConfigStore.swift].freeze
EXTENSION_SOURCES = %w[PacketTunnelProvider.swift].freeze

# Lives in the Runner group, alongside AppDelegate, because it is app code —
# but it is ours rather than something `flutter create` wrote, so this script
# is what puts it in the target.
CHANNEL_SOURCE = 'VpnChannel.swift'

abort "No project at #{PROJECT_PATH}" unless File.exist?(PROJECT_PATH)

project = Xcodeproj::Project.open(PROJECT_PATH)
runner = project.targets.find { |target| target.name == 'Runner' }
abort 'No Runner target in the project' if runner.nil?

# --- start from a clean slate ------------------------------------------------

def remove_target(project, runner, name)
  target = project.targets.find { |candidate| candidate.name == name }
  return if target.nil?

  runner.dependencies
        .select { |dependency| dependency.target == target }
        .each(&:remove_from_project)

  product = target.product_reference
  runner.build_phases.grep(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase).each do |phase|
    phase.files.select { |file| file.file_ref == product }.each(&:remove_from_project)
  end

  target.remove_from_project
  product&.remove_from_project
end

def remove_group(project, name)
  group = project.main_group.children.find do |child|
    child.is_a?(Xcodeproj::Project::Object::PBXGroup) && child.display_name == name
  end
  return if group.nil?

  group.children.to_a.each(&:remove_from_project)
  group.remove_from_project
end

# Dropping a group leaves the build files that pointed into it behind, still
# listed in whatever target compiled them but no longer under any group — and a
# file reference with no parent resolves against the project directory instead
# of the one it lives in. That reads as "build input file cannot be found" for a
# file that is plainly there, so every reference this script owns is purged by
# name before anything is rebuilt.
def purge_references(project, names)
  project.targets.each do |target|
    target.build_phases.each do |phase|
      next unless phase.respond_to?(:files)

      phase.files
           .select { |file| file.file_ref.nil? || names.include?(file.file_ref.display_name) }
           .each(&:remove_from_project)
    end
  end

  project.files
         .select { |file| names.include?(file.display_name) }
         .each(&:remove_from_project)
end

OWNED_FILES = (
  SHARED_SOURCES +
  EXTENSION_SOURCES +
  [
    CHANNEL_SOURCE,
    # Deliberately not Info.plist: Runner has one of its own, and purging by
    # name would take it too.
    "#{EXTENSION_NAME}.entitlements",
    "#{EXTENSION_NAME}-Bridging-Header.h",
    'VzhukhTunnelCore.xcframework',
    'NetworkExtension.framework',
  ]
).freeze

remove_target(project, runner, EXTENSION_NAME)
purge_references(project, OWNED_FILES)
remove_group(project, EXTENSION_NAME)
remove_group(project, SHARED_GROUP)

# --- what the app needs either way -------------------------------------------

def group_for(project, name)
  group = project.main_group.new_group(name, name)
  group.set_source_tree('SOURCE_ROOT')
  group
end

# The configuration model and its keychain store are needed on both sides: the
# app writes what the extension reads. They stay in the app target even when
# the extension is removed, so that VpnChannel still compiles — without the
# entitlement it fails at runtime with something legible instead of failing to
# build with something that is not.
shared_group = group_for(project, SHARED_GROUP)
shared_references = SHARED_SOURCES.map { |source| shared_group.new_reference(source) }
runner.add_file_references(shared_references)

runner_group = project.main_group.children.find { |child| child.display_name == 'Runner' }
abort 'No Runner group in the project' if runner_group.nil?
runner.add_file_references([runner_group.new_reference(CHANNEL_SOURCE)])

if ARGV.first == 'remove'
  # The entitlements go too. A profile that cannot carry them fails to build
  # even with the extension gone.
  runner.build_configurations.each do |configuration|
    configuration.build_settings.delete('CODE_SIGN_ENTITLEMENTS')
  end

  project.save

  puts "Removed #{EXTENSION_NAME} from Runner.xcodeproj"
  puts '  The app builds and runs; there is no tunnel in it.'
  puts "  Put it back with: just ios-tunnel-on"
  exit
end

# --- the extension target ----------------------------------------------------

extension = project.new_target(
  :app_extension,
  EXTENSION_NAME,
  :ios,
  DEPLOYMENT_TARGET,
  nil,
  :swift
)

extension.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings['PRODUCT_BUNDLE_IDENTIFIER'] = EXTENSION_BUNDLE_ID
  settings['PRODUCT_NAME'] = '$(TARGET_NAME)'
  settings['INFOPLIST_FILE'] = "#{EXTENSION_NAME}/Info.plist"
  settings['CODE_SIGN_ENTITLEMENTS'] = "#{EXTENSION_NAME}/#{EXTENSION_NAME}.entitlements"
  settings['CODE_SIGN_STYLE'] = 'Automatic'
  settings['DEVELOPMENT_TEAM'] = TEAM_ID
  settings['SWIFT_VERSION'] = '5.0'
  settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  settings['TARGETED_DEVICE_FAMILY'] = '1,2'
  settings['MARKETING_VERSION'] = '1.0.0'
  settings['CURRENT_PROJECT_VERSION'] = '1'
  settings['SKIP_INSTALL'] = 'YES'

  # Swift cannot see the kernel control socket types the utun lookup needs
  # without this; see the header itself for what and why.
  settings['SWIFT_OBJC_BRIDGING_HEADER'] = "#{EXTENSION_NAME}/#{EXTENSION_NAME}-Bridging-Header.h"

  # Where the Go archive lives, and what its C half needs at link time: Go's
  # resolver on Darwin goes through the system one, which lives in libresolv.
  settings['FRAMEWORK_SEARCH_PATHS'] = ['$(inherited)', '$(SRCROOT)/Frameworks']
  settings['OTHER_LDFLAGS'] = ['$(inherited)', '-lresolv']
end

# --- sources -----------------------------------------------------------------

extension_group = group_for(project, EXTENSION_NAME)
EXTENSION_SOURCES.each do |source|
  extension.add_file_references([extension_group.new_reference(source)])
end

# The same references the app compiles, not copies of them: one file, two
# targets, which is what keeps the two sides of the keychain agreeing.
extension.add_file_references(shared_references)

# Info.plist and entitlements belong in the group for visibility, but must not
# be compiled, so they are added as references only.
extension_group.new_reference('Info.plist')
extension_group.new_reference("#{EXTENSION_NAME}.entitlements")
extension_group.new_reference("#{EXTENSION_NAME}-Bridging-Header.h")

# --- libraries ---------------------------------------------------------------

extension.add_system_framework('NetworkExtension')

core = project.frameworks_group.new_reference("Frameworks/VzhukhTunnelCore.xcframework")
core.set_source_tree('SOURCE_ROOT')
extension.frameworks_build_phase.add_file_reference(core)

# --- wiring it into the app --------------------------------------------------

runner.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings['CODE_SIGN_ENTITLEMENTS'] = 'Runner/Runner.entitlements'
  settings['CODE_SIGN_STYLE'] = 'Automatic'
  settings['DEVELOPMENT_TEAM'] = TEAM_ID
end

embed = runner.build_phases.grep(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
              .find { |phase| phase.name == 'Embed App Extensions' }
embed ||= runner.new_copy_files_build_phase('Embed App Extensions')
embed.symbol_dst_subfolder_spec = :plug_ins

embedded = embed.add_file_reference(extension.product_reference)
embedded.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }

# Xcode reports "Cycle inside Runner" if the extension is copied into the app
# bundle after Flutter's Thin Binary script, which has already claimed that
# bundle as an output. A new copy phase lands at the end of the list, so it has
# to be moved ahead of that script.
thin_binary = runner.build_phases.index do |phase|
  phase.respond_to?(:name) && phase.name == 'Thin Binary'
end
runner.build_phases.move(embed, thin_binary) unless thin_binary.nil?

runner.add_dependency(extension)

project.save

puts "Added #{EXTENSION_NAME} (#{EXTENSION_BUNDLE_ID}) to Runner.xcodeproj"
puts "  team:       #{TEAM_ID}"
puts "  sources:    #{(EXTENSION_SOURCES + SHARED_SOURCES).join(', ')}"
puts "  links:      NetworkExtension, VzhukhTunnelCore.xcframework"
